{{- if .Values.buildNumbers.enable }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "buildnumbers.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "buildnumbers.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "buildnumbers.name" . }}
{{- end }}
