apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "gcJobs.name" . }}
  labels:
    app: jenkins-x-lighthouse-gcjobs
spec:
  concurrencyPolicy: {{ .Values.gcJobs.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.gcJobs.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.gcJobs.backoffLimit }}
      template:
        metadata:
          labels:
            app: {{ template "gcJobs.name" . }}
            release: {{ .Release.Name }}
{{- if .Values.gcJobs.podAnnotations }}
          annotations:
{{ toYaml .Values.gcJobs.podAnnotations | indent 12 }}
{{- end }}
        spec:
          containers:
            - command:
                - /home/jx/gc-jobs
              image: {{ tpl .Values.gcJobs.image.repository . }}:{{ tpl .Values.gcJobs.image.tag . }}
              imagePullPolicy: {{ tpl .Values.gcJobs.image.pullPolicy . }}
              args:
                - "--namespace={{ .Release.Namespace }}"
                - "--max-age={{ .Values.gcJobs.maxAge }}"
              env:
              - name: LOG_LEVEL
                value: "{{ .Values.gcJobs.logLevel }}"
              name: {{ template "gcJobs.name" . }}
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          serviceAccountName: {{ template "gcJobs.name" . }}
  successfulJobsHistoryLimit: {{ .Values.gcJobs.successfulJobsHistoryLimit }}
  schedule: {{ .Values.gcJobs.schedule | quote }}
  startingDeadlineSeconds: 4000
  suspend: false
