apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "keeper.name" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "keeper.name" . }}
spec:
  replicas: {{ .Values.keeper.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "keeper.name" . }}
  template:
    metadata:
{{- if or .Values.keeper.datadog.enabled .Values.keeper.podAnnotations }}
      annotations:
{{- if .Values.keeper.datadog.enabled }}
        ad.datadoghq.com/keeper.logs: '[{"source":"lighthouse","service":"keeper"}]'
{{- end }}
{{- if .Values.keeper.podAnnotations }}
{{ toYaml .Values.keeper.podAnnotations | indent 8 }}
{{- end }}
{{- end }}
      labels:
        app: {{ template "keeper.name" . }}
    spec:
      serviceAccountName: {{ template "keeper.name" . }}
      terminationGracePeriodSeconds: {{ .Values.keeper.terminationGracePeriodSeconds }}
      containers:
      - name: {{ template "keeper.name" . }}
        image: {{ tpl .Values.keeper.image.repository . }}:{{ tpl .Values.keeper.image.tag . }}
        imagePullPolicy: {{ tpl .Values.keeper.image.pullPolicy . }}
        args:
          - "--namespace={{ .Release.Namespace }}"
        ports:
          - name: http
            containerPort: {{ .Values.keeper.service.internalPort }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.keeper.probe.path }}
            port: http
          initialDelaySeconds: {{ .Values.keeper.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.keeper.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.keeper.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.keeper.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.keeper.probe.path }}
            port: http
          periodSeconds: {{ .Values.keeper.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.keeper.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.keeper.readinessProbe.timeoutSeconds }}
        env:
        - name: "GIT_KIND"
          value: "{{ .Values.git.kind }}"
        - name: "GIT_SERVER"
          value: "{{ .Values.git.server }}"
{{- if .Values.githubApp.enabled }}
        - name: "GITHUB_APP_SECRET_DIR"
          value: "/secrets/githubapp/tokens"
{{- else }}
        - name: "GIT_USER"
          value: {{ .Values.user }}
{{- if .Values.oauthTokenVolumeMount.enabled }}
        - name: "GIT_TOKEN_PATH"
          value: /secrets/lighthouse-oauth-token/oauth
{{- else }}
        - name: "GIT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.oauthSecretName | default "lighthouse-oauth-token" }}
              key: oauth
{{- end }}
{{- end }}
        - name: "JX_LOG_FORMAT"
          value: "{{ .Values.logFormat }}"
        - name: LOG_LEVEL
          value: "{{ .Values.keeper.logLevel }}"
        - name: "LOGRUS_FORMAT"
          value: "{{ .Values.logFormat }}"
        - name: LOGRUS_SERVICE
          value: "{{ .Values.logService | default .Chart.Name }}"
        - name: LOGRUS_SERVICE_VERSION
          value: "{{ .Chart.Version }}"
        - name: LOGRUS_STACK_SKIP
          value: "{{ .Values.logStackSkip }}"
        - name: "LIGHTHOUSE_KEEPER_STATUS_CONTEXT_LABEL"
          value: "{{ .Values.keeper.statusContextLabel}}"
{{- if hasKey .Values.keeper "env" }}
{{- range $pkey, $pval := .Values.keeper.env }}
        - name: {{ $pkey }}
          value: {{ quote  $pval }}
{{- end }}
{{- end }}
        envFrom:
        - secretRef:
            name: jx-boot-job-env-vars
            optional: true
        resources:
{{ toYaml .Values.keeper.resources | indent 10 }}
        volumeMounts:
{{- if .Values.githubApp.enabled }}
        - name: githubapp-tokens
          mountPath: /secrets/githubapp/tokens
          readOnly: true
{{- else if .Values.oauthTokenVolumeMount.enabled }}
        - name: lighthouse-oauth-token
          mountPath: /secrets/lighthouse-oauth-token
          readOnly: true
{{- end }}
      volumes:
{{- if .Values.githubApp.enabled }}
      - name: githubapp-tokens
        secret:
          secretName: tide-githubapp-tokens
{{- else if .Values.oauthTokenVolumeMount.enabled }}
      - name: lighthouse-oauth-token
        secret:
          secretName: lighthouse-oauth-token
{{- end }}
{{- with .Values.keeper.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.keeper.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.keeper.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
