{{- /*
Only create the "plugins" ConfigMap on install, so that we don't overwrite it on upgrade.
*/ -}}
{{- if and .Values.configMaps.create (or (not .Release.IsUpgrade) .Values.configMaps.plugins) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
data:
{{- if .Values.configMaps.plugins }}
  plugins.yaml: |
{{ .Values.configMaps.plugins | indent 4 }}
{{- else }}
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos: []
      # repos are specified here as:
      # - org/repo
      require_self_approval: true
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
{{- if ne .Values.configMaps.configUpdater.path "" }}
      maps:
        {{ .Values.configMaps.configUpdater.path }}/config.yaml:
          name: config
        {{ .Values.configMaps.configUpdater.path }}/plugins.yaml:
          name: plugins
{{- else }}
      maps: {}
{{- end }}
    external_plugins: {}
    heart: {}
    label:
      additional_labels: null
    owners: {}
{{- if ne .Values.configMaps.configUpdater.orgAndRepo "" }}
    plugins:
      {{ .Values.configMaps.configUpdater.orgAndRepo }}:
      - config-updater
{{- else }}
    plugins: {}
{{- end }}
    # Example of configuration for a repository
    # org/repo:
    #   - approve
    #   - assign
    #   - cat
    #   - dog
    #   - help
    #   - hold
    #   - label
    #   - lgtm
    #   - lifecycle
    #   - override
    #   - pony
    #   - shrug
    #   - size
    #   - skip
    #   - trigger
    #   - wip
    #   - yuks
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    triggers: []
    # Example triggers configuration:
    # - repos:
    #     - org/repo
    #   trusted_org: org
    welcome:
    - message_template: Welcome
{{- end }}
{{- end }}
