{{- if .Values.engines.tekton }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tektoncontroller.name" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "tektoncontroller.name" . }}
spec:
  replicas: {{ .Values.tektoncontroller.replicaCount }}
  selector:
    matchLabels:
      draft: {{ default "draft-app" .Values.draft }}
      app: {{ template "tektoncontroller.name" . }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "tektoncontroller.name" . }}
      annotations:
        {{- toYaml .Values.tektoncontroller.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ template "tektoncontroller.name" . }}
      containers:
      - name: {{ template "tektoncontroller.name" . }}
        image: {{ printf "%s:%s" (tpl .Values.tektoncontroller.image.repository .) (tpl .Values.tektoncontroller.image.tag .) }}
        imagePullPolicy: {{ tpl .Values.tektoncontroller.image.pullPolicy . }}
        args:
          - --namespace={{ .Release.Namespace }}
          - --dashboard-url={{ .Values.tektoncontroller.dashboardURL }}
        ports:
          - name: metrics
            containerPort: 8080
        env:
          - name: "LOGRUS_FORMAT"
            value: "{{ .Values.logFormat }}"
          {{- range $pkey, $pval := .Values.env }}
          - name: {{ $pkey }}
            value: {{ quote $pval }}
          {{- end }}
        resources:
          {{- toYaml .Values.tektoncontroller.resources | nindent 12 }}
      terminationGracePeriodSeconds: {{ .Values.tektoncontroller.terminationGracePeriodSeconds }}
      nodeSelector:
        {{- toYaml .Values.tektoncontroller.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.tektoncontroller.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tektoncontroller.tolerations | nindent 8 }}
{{- end }}
