{{- if .Values.engines.tekton }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tektoncontroller.name" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "tektoncontroller.name" . }}
spec:
  replicas: {{ .Values.tektoncontroller.replicaCount }}
  selector:
    matchLabels:
      draft: {{ default "draft-app" .Values.draft }}
      app: {{ template "tektoncontroller.name" . }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "tektoncontroller.name" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "tektoncontroller.name" . }}
      containers:
      - name: {{ template "tektoncontroller.name" . }}
        image: {{ tpl .Values.tektoncontroller.image.repository . }}:{{ tpl .Values.tektoncontroller.image.tag . }}
        imagePullPolicy: {{ tpl .Values.tektoncontroller.image.pullPolicy . }}
        args:
          - "--namespace={{ .Release.Namespace }}"
        env:
          - name: "LOGRUS_FORMAT"
            value: "{{ .Values.logFormat }}"
{{- if hasKey .Values "env" }}
{{- range $pkey, $pval := .Values.env }}
          - name: {{ $pkey }}
            value: {{ quote $pval }}
{{- end }}
{{- end }}
{{- with .Values.tektoncontroller.resources }}
        resources:
{{ toYaml . | indent 12 }}
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.tektoncontroller.terminationGracePeriodSeconds }}
{{- with .Values.tektoncontroller.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tektoncontroller.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tektoncontroller.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
