apiVersion: v1
appVersion: 0.0.843
description: |
  This chart bootstraps installation of [Lighthouse](https://github.com/jenkins-x/lighthouse).
home: https://github.com/jenkins-x/lighthouse
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-website/master/images/logo/jenkinsx-icon-color.svg
name: lighthouse
version: 0.0.843
